pipeline {

    agent any

    

    environment {

        DOCKER_IMAGE = 'blogapp/blog-app'  

        DOCKER_TAG = "${env.BUILD_NUMBER}"

    }

    

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        

        stage('Build') {

            steps {

                sh 'mkdir -p ${WORKSPACE}/.m2'

                dir('backend') {

                    sh '''

                        docker run --rm -v ${WORKSPACE}/backend:/app -v ${WORKSPACE}/.m2:/root/.m2 -w /app maven:3.9-eclipse-temurin-17 mvn clean package -DskipTests -B

                    '''

                }

            }

        }

        

        stage('Test') {

            steps {

                dir('backend') {

                    sh '''

                        docker run --rm -v ${WORKSPACE}/backend:/app -v ${WORKSPACE}/.m2:/root/.m2 -w /app maven:3.9-eclipse-temurin-17 mvn test

                    '''

                }

            }

            post {

                always {

                    junit 'backend/target/surefire-reports/**/*.xml'

                }

            }

        }

        

        stage('Package') {

            steps {

                dir('backend') {

                    sh '''

                        docker run --rm -v ${WORKSPACE}/backend:/app -v ${WORKSPACE}/.m2:/root/.m2 -w /app maven:3.9-eclipse-temurin-17 mvn -ntp -Pprod clean package -DskipTests

                    '''

                }

            }

        }

        

        stage('Publish Docker Image') {

            steps {

                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]) {

                    dir('backend') {

                        sh """

                            docker run --rm -v \${WORKSPACE}/backend:/app -v \${WORKSPACE}/.m2:/root/.m2 -w /app -e DOCKER_REGISTRY_USER=\${DOCKER_REGISTRY_USER} -e DOCKER_REGISTRY_PWD=\${DOCKER_REGISTRY_PWD} maven:3.9-eclipse-temurin-17 mvn -ntp jib:build -Djib.to.image=${DOCKER_IMAGE}:${DOCKER_TAG} -Djib.to.tags=latest,${DOCKER_TAG}

                        """

                    }

                }

            }

        }

    }

    

    post {

        success {

            echo ":white_check_mark: Pipeline completed successfully! Image: ${DOCKER_IMAGE}:${DOCKER_TAG}"

        }

        failure {

            echo ":x: Pipeline failed!"

        }

        always {

            // Limpiar workspace con manejo de errores

            script {

                try {

                    cleanWs()

                } catch (Exception e) {

                    echo ":warning: No se pudo limpiar el workspace: ${e.message}"

                }

            }

        }

    }

}

